"""test split

Revision ID: 2ef27328fd0c
Revises: 966beec7a0bb
Create Date: 2026-06-02 00:28:34.379754

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2ef27328fd0c'
down_revision: str | Sequence[str] | None = '966beec7a0bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
