"""add issuer inn and is_public

Revision ID: 398cc1299bc4
Revises: 2ef27328fd0c
Create Date: 2026-06-02 00:42:09.000660

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '398cc1299bc4'
down_revision: str | Sequence[str] | None = '2ef27328fd0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issuers', sa.Column('inn', sa.String(length=12), nullable=True))
    op.add_column(
        'issuers',
        sa.Column(
            'is_public',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
        ),
    )
    op.create_index(op.f('ix_issuers_inn'), 'issuers', ['inn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issuers_inn'), table_name='issuers')
    op.drop_column('issuers', 'is_public')
    op.drop_column('issuers', 'inn')
    # ### end Alembic commands ###
