"""add risk score columns and checks

Revision ID: 431f85a692f4
Revises: c71b814151b4
Create Date: 2026-05-28 17:35:42.945987

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '431f85a692f4'
down_revision: str | Sequence[str] | None = 'c71b814151b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_reports', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('risk_reports', sa.Column('coverage_penalty', sa.Float(), nullable=True))
    op.drop_column('risk_reports', 'overall_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'risk_reports',
        sa.Column(
            'overall_score',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column('risk_reports', 'coverage_penalty')
    op.drop_column('risk_reports', 'risk_score')
    # ### end Alembic commands ###
