"""add risk score check constraints

Revision ID: c71b814151b4
Revises: c8a16ed2243a
Create Date: 2026-05-28 16:33:02.451745

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c71b814151b4'
down_revision: str | Sequence[str] | None = 'c8a16ed2243a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'agent_traces',
        sa.Column(
            'input_',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.drop_column('agent_traces', 'input')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'agent_traces',
        sa.Column(
            'input',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column('agent_traces', 'input_')
    # ### end Alembic commands ###
