"""add jsonb fields

Revision ID: c8a16ed2243a
Revises: e71ee972dcd9
Create Date: 2026-05-28 15:02:28.141238

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8a16ed2243a'
down_revision: str | Sequence[str] | None = 'e71ee972dcd9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_JSONB = postgresql.JSONB(astext_type=sa.Text())
_EMPTY_OBJECT = sa.text("'{}'::jsonb")
_EMPTY_ARRAY = sa.text("'[]'::jsonb")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'agent_traces',
        sa.Column('input', _JSONB, server_default=_EMPTY_OBJECT, nullable=False),
    )
    op.add_column(
        'agent_traces',
        sa.Column('output', _JSONB, nullable=True),
    )
    op.add_column(
        'agent_traces',
        sa.Column(
            'retrieved_chunk_ids',
            _JSONB,
            server_default=_EMPTY_ARRAY,
            nullable=False,
        ),
    )
    op.drop_column('agent_traces', 'input_payload')
    op.drop_column('agent_traces', 'output_payload')
    op.add_column(
        'documents',
        sa.Column('metadata', _JSONB, server_default=_EMPTY_OBJECT, nullable=False),
    )
    op.add_column(
        'ingestion_jobs',
        sa.Column('payload', _JSONB, server_default=_EMPTY_OBJECT, nullable=False),
    )
    op.add_column(
        'risk_reports',
        sa.Column('metadata', _JSONB, server_default=_EMPTY_OBJECT, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_reports', 'metadata')
    op.drop_column('ingestion_jobs', 'payload')
    op.drop_column('documents', 'metadata')
    op.add_column(
        'agent_traces',
        sa.Column('output_payload', _JSONB, autoincrement=False, nullable=True),
    )
    op.add_column(
        'agent_traces',
        sa.Column('input_payload', _JSONB, autoincrement=False, nullable=False),
    )
    op.drop_column('agent_traces', 'retrieved_chunk_ids')
    op.drop_column('agent_traces', 'output')
    op.drop_column('agent_traces', 'input')
    # ### end Alembic commands ###
